/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.boxcf.components.material;

import com.boxcf.models.ModelStatistical;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;

/**
 *
 * @author PC
 */
public class CategoryChartItem extends javax.swing.JPanel {

    private boolean active;
    private ModelStatistical data;

    public CategoryChartItem() {
        initComponents();
        setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();

        setBackground(new java.awt.Color(220, 220, 220));
        setForeground(new java.awt.Color(151, 151, 151));
        setMaximumSize(new java.awt.Dimension(200, 40));
        setMinimumSize(new java.awt.Dimension(200, 40));
        setPreferredSize(new java.awt.Dimension(200, 40));

        lblTitle.setFont(new java.awt.Font("UTM Aptima", 1, 14)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(153, 153, 153));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public boolean isActive() {
        return active;
    }

    public ModelStatistical getData() {
        return data;
    }

    public void setData(ModelStatistical data) {
        this.data = data;
    }

    public void addData(ModelStatistical data) {
        this.data = data;
        lblTitle.setText(data.getCategory());
    }

    public void setActive(boolean active) {
        this.active = active;
        if (active) {
            lblTitle.setForeground(new Color(255, 255, 255));
            this.setBackground(new Color(56, 187, 156));
            this.setCursor(new Cursor(Cursor.HAND_CURSOR));
        } else {
            lblTitle.setForeground(new Color(153, 153, 153));
            this.setBackground(new Color(220, 220, 220));
            this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        }
        repaint();
    }

    public void hoverIn() {
        lblTitle.setForeground(new Color(255, 255, 255));
        this.setBackground(new Color(56, 187, 156));
        this.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }

    public void hoverOut() {
        if (active) {
            return;
        }
        lblTitle.setForeground(new Color(153, 153, 153));
        this.setBackground(new Color(220, 220, 220));
        this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }

    public void toggle() {
        this.active = !active;
        setActive(active);
    }

    @Override
    public void paint(Graphics grphcs) {
        Graphics2D g2 = (Graphics2D) grphcs.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(getBackground());
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 10, 10);
        super.paint(grphcs);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
