
package com.boxcf.components;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFrame;

/**
 *
 * @author PC
 */
public class ClsoeButton extends javax.swing.JPanel {

    /**
     * Creates new form ClsoeButton
     */
    public ClsoeButton() {
        initComponents();
        btnClose.setBackground(new Color(0, 0, 0, 0));
        hover();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnClose = new com.boxcf.components.ButtonRound();

        setMinimumSize(new java.awt.Dimension(12, 12));
        setPreferredSize(new java.awt.Dimension(20, 20));

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/boxcf/images/icon/close.png"))); // NOI18N
        btnClose.setFocusPainted(false);
        btnClose.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClose.setPreferredSize(new java.awt.Dimension(24, 24));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnClose, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnClose, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.boxcf.components.ButtonRound btnClose;
    // End of variables declaration//GEN-END:variables

    public void hover() {
        btnClose.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                btnClose.setBackground(Color.decode("#cccccc"));
                btnClose.setIcon(new ImageIcon(getClass().getResource("/com/boxcf/images/icon/re-close.png")));
            }

            @Override
            public void mouseExited(MouseEvent e) {
                btnClose.setBackground(new Color(0, 0, 0, 0));
                btnClose.setIcon(new ImageIcon(getClass().getResource("/com/boxcf/images/icon/close.png")));

            }

        });

    }

    public void initEvent(JFrame fram) {
        btnClose.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                fram.dispose();
            }
        });

    }
    
    public void initEvent(JDialog fram) {
        btnClose.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                fram.dispose();
            }
        });

    }
}
